services:
  cid-comparison:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    #   args:
    #     PUID: 1000
    #     PGID: 1000
    #     UMASK: "022"
    #     GOLOG_LOG_LEVEL: info
    #     GOLOG_LOG_FMT: color
    image: cid-comparison:latest
    container_name: cid-comparison
    hostname: cid-comparison
    restart: unless-stopped
    ports:
      - "9090:9090"    # Singularity API
      - "5001:5001"    # IPFS API
      - "8080:8080"    # IPFS Gateway (optional)
    volumes:
      - ./data:/data
      - ./config_test:/home/appuser/config
    environment:
      - GOLOG_LOG_LEVEL=info
      - GOLOG_LOG_FMT=color
      # Uncomment one of these for auto-run mode:
      # - CID_AUTO_RUN=full-pipeline
      # - CID_AUTO_RUN=shell
      # - CID_AUTO_RUN=prepare-data
    stdin_open: true
    tty: true

volumes:
  data:
    driver: local
  config:
    driver: local