services:
  singularity-downloader:
    build: .
    container_name: singularity-downloader
    volumes:
      - ./downloads:/downloads
      - ./configs:/app/configs
    environment:
      - TZ=UTC
      # Optional: Set custom endpoints via environment variables
      # - SINGULARITY_API_HOST=http://your-api-server:9090 
      # - SINGULARITY_DOWNLOAD_HOST=http://your-download-server:7777
    # Resource limits to ensure sufficient capacity for concurrent downloads
    # deploy:
    #   resources:
    #     limits:
    #       memory: 4G
    #     reservations:
    #       memory: 1G
    # Increase process and file descriptor limits
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
    # Use host networking for better concurrent connection performance
    # network_mode: host  # Uncomment if needed for better networking
    # Remove the automatic download command to keep container running
    # command: ["./download-pieces.sh", "1", "8", "/downloads"]
    stdin_open: true
    tty: true
